services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend-dev.Dockerfile
    container_name: frontend-dev
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  backend:
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npx", "nodemon", "app.js"]