services:
  couchdb:
    image: couchdb:3.4.3
    container_name: couchdb
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    volumes:
      - couchdb_data:/opt/couchdb/data # Data persistency

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   container_name: backend
  #   ports:
  #   environment:
  #     - COUCHDB_URL=http://couchdb:5984
  #     - COUCHDB_USER=admin
  #     - COUCHDB_PASSWORD=admin
  #     - COUCHDB_DATABASE=mantenimientos_coches
  #   depends_on:
  #     - couchdb # CouchDB needs to be running before the backend
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: frontend
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend # Backend needs to be running before the frontend
volumes:
  couchdb_data: