services:
  couchdb:
    image: couchdb:3.4.3
    container_name: couchdb
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      - couchdb_data:/opt/couchdb/data # Data persistency

  init-couchdb:
    build:
      context: .
      dockerfile: docker/init.Dockerfile
    container_name: init-couchdb
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    depends_on:
      - couchdb
    restart: "no"
      

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - COUCHDB_URL=${COUCHDB_URL}
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_DATABASE=${COUCHDB_DATABASE}
    depends_on:
      - couchdb # CouchDB needs to be running before the backend
      - init-couchdb # Init script needs to run before the backend


  #frontend:
  #  build:
  #    context: ./frontend
  #    dockerfile: Dockerfile
  #  container_name: frontend
  #  ports:
  #    - "80:80"
  #  depends_on:
  #    - backend # Backend needs to be running before the frontend
volumes:
  couchdb_data: