services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend-dev.Dockerfile
    container_name: frontend-dev
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development