module.exports = [
  {
    _id: "maint_123",
    userId: "org.couchdb.user:johndoe",
    brand: "Toyota",
    model: "Corolla",
    licensePlate: "1234-ABC",
    maintenanceDate: "2025-04-15",
    maintenanceType: ["Oil Change"],
    cost: 150,
    comments: "Regular maintenance",
    createdAt: "2025-04-20T12:00:00Z",
  },
  {
    _id: "maint_124",
    userId: "org.couchdb.user:janedoe",
    brand: "Honda",
    model: "Civic",
    licensePlate: "5678-DEF",
    maintenanceDate: "2025-05-20",
    maintenanceType: ["Tire Rotation", "Fluid Check"],
    cost: 100,
    comments: "Performed at ABC Auto Service",
    createdAt: "2025-05-21T10:30:00Z",
  },
  {
    _id: "maint_125",
    userId: "org.couchdb.user:johndoe",
    brand: "Ford",
    model: "Focus",
    licensePlate: "9101-GHI",
    maintenanceDate: "2025-06-10",
    maintenanceType: ["Battery Replacement"],
    cost: 200,
    comments: "Performed at DEF Garage",
    createdAt: "2025-06-11T08:00:00Z",
  },
  {
    _id: "maint_126",
    userId: "org.couchdb.user:alexsmith",
    brand: "Chevrolet",
    model: "Malibu",
    licensePlate: "1122-JKL",
    maintenanceDate: "2025-07-05",
    maintenanceType: ["Brake Pad Replacement"],
    cost: 250,
    comments: "Performed at GHI Auto Repair",
    createdAt: "2025-07-06T14:45:00Z",
  },
  {
    _id: "maint_127",
    userId: "org.couchdb.user:emilywhite",
    brand: "Nissan",
    model: "Altima",
    licensePlate: "3344-MNO",
    maintenanceDate: "2025-08-15",
    maintenanceType: ["Transmission Fluid Change"],
    cost: 300,
    comments: "Performed at JKL Service Center",
    createdAt: "2025-08-16T12:20:00Z",
  },
  {
    _id: "maint_128",
    userId: "org.couchdb.user:johndoe",
    brand: "Toyota",
    model: "Prius",
    licensePlate: "7788-XYZ",
    maintenanceDate: "2025-09-01",
    maintenanceType: ["Air Filter Change", "Coolant Check"],
    cost: 120,
    comments: "All filters replaced",
    createdAt: "2025-09-01T09:00:00Z",
  },
  {
    _id: "maint_129",
    userId: "org.couchdb.user:alexsmith",
    brand: "Hyundai",
    model: "Elantra",
    licensePlate: "5566-POI",
    maintenanceDate: "2025-10-12",
    maintenanceType: ["Spark Plug Replacement"],
    cost: 90,
    comments: "Spark plugs changed during routine check",
    createdAt: "2025-10-12T10:15:00Z",
  },
  {
    _id: "maint_130",
    userId: "org.couchdb.user:emilywhite",
    brand: "Volkswagen",
    model: "Golf",
    licensePlate: "2233-LMN",
    maintenanceDate: "2025-11-03",
    maintenanceType: ["Wheel Alignment"],
    cost: 110,
    comments: "Alignment done after tire change",
    createdAt: "2025-11-03T11:40:00Z",
  },
];
